server:
  port: 8762

#指明spring.application.name很重要，后边服务之间相互调用一般根据该name
spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://peer1:8761/eureka/


